pipeline {
    agent any
    environment {
        REGISTRY = "harbor.mycompany.com"
        BACKEND_IMAGE = "video-spring-backend"
        VERSION = "0.0.1"
    }
    stages {
        stage('Checkout') {
            steps {
                git branch: 'develop', url: 'https://github.com/jasminemai77/video-spring.git'
            }
        }
        stage('Build Backend') {
            steps {
                dir('video-spring') { // 进入子目录
                    sh 'mvn clean package -DskipTests'
                    sh "docker build -t ${REGISTRY}/${BACKEND_IMAGE}:${VERSION} ."
                    sh "docker push ${REGISTRY}/${BACKEND_IMAGE}:${VERSION}"
                }
            }
        }
        stage('Deploy') {
            steps {
                sh """
                ssh deploy@server 'cd /opt/video-spring && \
                docker-compose down && \
                docker-compose pull && \
                docker-compose up -d'
                """
            }
        }
        stage('Notify') {
            steps {
                echo "部署完成"
            }
        }
    }
}
